description: Hi welcome to my Github-pages
title: Mochammad Farkhan
# Site settings
email: mochammadfarkhan@gmail.com
twitter_username: khan
github_username:  mochammadfarkhan

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.17.1"
