description: Hi welcome to my Github-pages
title: Mochammad Farkhan
# Site settings
email: lbogoev@mit.edu
twitter_username: khan
github_username:  mochammadfarkhan

# Build settings
markdown: kramdown
